[[scripts]]
  triggers = ["on-start", "pre b", "script audio", "interval 750ms"]
  name = "bluetooth"
  path = "menu-bluetooth"
  colour = 3
  stay_open = true

[[scripts]]
  triggers = ["on-start", "pre a", "script bluetooth", "interval 750ms"]
  name = "audio"
  path = "menu-audio"
  colour = 6
  stay_open = true

[[scripts]]
  triggers = ["on-start"]
  name = "sway"
  path = "menu-sway"
  colour = 5
  columns = [2, 3]

[[scripts]]
  triggers = ["on-start", "pre p"]
  name = "package"
  path = "menu-package"
  colour = 7
  columns = [1, 2]

[[scripts]]
  triggers = ["pre pw", "pre pass"]
  name = "pass"
  path = "menu-pass"
  colour = 12
  columns = [2, 3, 4]

[[scripts]]
  triggers = ["pre c"]
  name = "clipboard"
  path = "menu-clipboard"
  colour = 11

[[scripts]]
  triggers = ["pre e"]
  name = "emoji"
  path = "menu-emoji"
  colour = 12

[[scripts]]
  triggers = ["pre w", "interval 1s"]
  name = "wifi"
  path = "menu-wifi"
  colour = 10
  stay_open = true

[[scripts]]
  triggers = ["pre r"]
  name = "radio"
  path = "menu-radio"
  colour = 1
  stay_open = true

[[scripts]]
  triggers = ["pre v"]
  name = "virt"
  path = "menu-virt"
  colour = 5

[[scripts]]
  triggers = ["pre s"]
  name = "scrot"
  path = "menu-scrot"
  colour = 6

[[scripts]]
  triggers = ["pre td"]
  name = "tuned"
  path = "menu-tuned"
  colour = 7

[[scripts]]
  triggers = ["pre cc", "input"]
  name = "calc"
  path = "menu-calc"
  colour = 2

[[scripts]]
  triggers = ["pre hh", "input"]
  name = "hiphash"
  path = "menu-hiphash"
  colour = 2

[[scripts]]
  triggers = ["pre lm", "input 500ms"]
  name = "llm"
  path = "menu-llm"
  colour = 2
  stay_open = true
